package com.sofrecom.codegen.launcher;

import java.awt.Component;
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author z.benrhouma
 */
public class DTOLoader extends javax.swing.JFrame {

    /**
     * Creates new form DTOLoader
     */
    public DTOLoader() {
        initComponents();
        this.loadUIConfiguration();
        this.verifyClassesDireectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        tableNamelabel1 = new javax.swing.JLabel();
        outpathTextField = new javax.swing.JTextField();
        cutomizeOutPathButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        generateViewModelBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 250, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("You Shoul Generate DTO .classe files before you can load View Model the source file.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jSeparator1.setPreferredSize(new java.awt.Dimension(1, 1));
        getContentPane().add(jSeparator1);

        tableNamelabel1.setText("Class Directory Path");

        outpathTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                outpathTextFieldCaretUpdate(evt);
            }
        });

        cutomizeOutPathButton.setText("...");
        cutomizeOutPathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutomizeOutPathButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tableNamelabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(outpathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cutomizeOutPathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outpathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cutomizeOutPathButton)
                    .addComponent(tableNamelabel1))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        jSeparator2.setPreferredSize(new java.awt.Dimension(1, 1));
        getContentPane().add(jSeparator2);

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 50));

        generateViewModelBtn.setText("Ok");
        generateViewModelBtn.setEnabled(false);
        generateViewModelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateViewModelBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(464, Short.MAX_VALUE)
                .addComponent(generateViewModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(generateViewModelBtn))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>                        

    private void cutomizeOutPathButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      

        final File directoryChoice = this.getDirectoryChoice(this, Configuration.getProperty(Configuration.LastUsedOutputpath), "Choose output directory");
        if (directoryChoice != null) {
            this.outpathTextField.setText(directoryChoice.getAbsolutePath());
        }
    }                                                     

    private void generateViewModelBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        
    	
        Configuration.setProperty(Configuration.LastUsedClassPath, outpathTextField.getText());
        Configuration.saveConfiguration();

    }                                                    

    private void outpathTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {                                             
        // TODO add your handling code here:
        verifyClassesDireectory();
    }                                            

    /**
     * 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setVisible(false);
        this.dispose();
    }                                        
    
    public File getDirectoryChoice(Component owner, String defaultDirectory,String title) {
        final SecurityManager sm = System.getSecurityManager();
        final JFileChooser chooser = new JFileChooser();
        File choiceFile = null;

        System.setSecurityManager(null);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        final File defaultDir = new File(defaultDirectory);
        if (defaultDir.exists() && defaultDir.isDirectory()) {
            chooser.setCurrentDirectory(defaultDir);
            chooser.setSelectedFile(defaultDir);
        }
        chooser.setDialogTitle(title);
        chooser.setApproveButtonText("OK");
        final int choice = chooser.showOpenDialog(owner);
        owner.requestFocus();
        switch (choice) {
            case JFileChooser.APPROVE_OPTION:
                if (chooser.getSelectedFile() != null) {
                    if (chooser.getSelectedFile().exists()) {
                        choiceFile = chooser.getSelectedFile();
                        Configuration.setProperty(Configuration.LastUsedClassPath, choiceFile.getAbsolutePath());
                    } else {
                        File parentFile = new File(chooser.getSelectedFile().getParent());
                        choiceFile = parentFile;
                    }
                }
                break;
            case JFileChooser.CANCEL_OPTION:
            case JFileChooser.ERROR_OPTION:
        }
        chooser.removeAll();
        System.setSecurityManager(sm);

        return choiceFile;
    }

    private void loadUIConfiguration() {
        Configuration.loadConfiguration();
        this.outpathTextField.setText(Configuration.getProperty(Configuration.LastUsedClassPath));
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton cutomizeOutPathButton;
    private javax.swing.JButton generateViewModelBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField outpathTextField;
    private javax.swing.JLabel tableNamelabel1;
    // End of variables declaration                   

    private void verifyClassesDireectory() {
        File classDirectory = new File(this.outpathTextField.getText());
        if (classDirectory.exists() && classDirectory.getAbsolutePath().endsWith("classes")) {
            this.generateViewModelBtn.setEnabled(true);
        } else {
            this.generateViewModelBtn.setEnabled(false);
        }
    }
    
    
    public static void main(String[] args) {
    	  try {
              JFrame.setDefaultLookAndFeelDecorated(true);
              javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

              /* Create and display the form */
              java.awt.EventQueue.invokeLater(new Runnable() {
                  @Override
                  public void run() {
                	  new DTOLoader().setVisible(true);
                  }
              });
          } catch (UnsupportedLookAndFeelException ex) {
              ex.printStackTrace();
          } catch (ClassNotFoundException e) {

			e.printStackTrace();
		} catch (InstantiationException e) {

			e.printStackTrace();
		} catch (IllegalAccessException e) {

			e.printStackTrace();
		}
		
	}
}
